services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver_1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!@
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    user: "0:0"   # Run as root

volumes:
  sqlserver_data: